import process from 'bare-process'
import b4a from 'b4a'
import Request from 'bare-fetch/request'
import { ReadableStream } from 'bare-stream/web'

import { Server } from 'SERVER'
import { manifest, prerendered, base } from 'MANIFEST'
// Auto-generated by adapter-bare. Embeds every static file as base64.
import { client, prerendered as prerendered_files } from './assets.js'

/** @param {Record<string, string>} files @returns {Record<string, Uint8Array>} */
function decode_assets(files) {
  /** @type {Record<string, Uint8Array>} */
  const out = {}
  for (const key of Object.keys(files)) out[key] = b4a.from(files[key], 'base64')
  return out
}

const client_assets = decode_assets(client)
const prerendered_assets = decode_assets(prerendered_files)

const server = new Server(manifest)

await server.init({
  env: /** @type {Record<string, string>} */ (process.env),
  read: (file) =>
    new ReadableStream({
      start(controller) {
        const key = (base ? base.replace(/^\//, '') + '/' : '') + file
        const buffer = client_assets[key]
        if (!buffer) return controller.error(new Error('asset not found: ' + key))
        controller.enqueue(buffer)
        controller.close()
      }
    })
})

/** @type {Record<string, string>} */
const MIMES = {
  html: 'text/html; charset=utf-8',
  js: 'text/javascript',
  mjs: 'text/javascript',
  css: 'text/css',
  json: 'application/json',
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  svg: 'image/svg+xml',
  ico: 'image/x-icon',
  woff: 'font/woff',
  woff2: 'font/woff2',
  ttf: 'font/ttf',
  wasm: 'application/wasm',
  webmanifest: 'application/manifest+json',
  txt: 'text/plain'
}

/** @param {string} filepath */
function get_mime(filepath) {
  const ext = filepath.split('.').pop()?.toLowerCase() ?? ''
  return MIMES[ext] ?? 'application/octet-stream'
}

/**
 * @param {Record<string, Uint8Array>} assets  map of URL-relative path → content
 * @param {{ immutable?: boolean }} [opts]
 */
function serve_assets(assets, opts = {}) {
  return (/** @type {any} */ req, /** @type {any} */ res, /** @type {() => void} */ next) => {
    const url = req.url.split('?')[0]
    let pathname
    try {
      pathname = decodeURIComponent(url)
    } catch {
      pathname = url
    }

    // Drop leading / and optional base prefix
    let key = pathname.replace(/^\//, '')
    if (base && key.startsWith(base.replace(/^\//, '') + '/')) {
      key = key.slice(base.replace(/^\//, '').length + 1)
    }

    let buffer = assets[key]
    if (!buffer && (key === '' || key.endsWith('/'))) {
      key += 'index.html'
      buffer = assets[key]
    }
    if (!buffer) return next()

    /** @type {Record<string, string | number>} */
    const headers = {
      'Content-Type': get_mime(key),
      'Content-Length': buffer.byteLength
    }
    if (opts.immutable && pathname.startsWith(`/${manifest.appPath}/immutable/`)) {
      headers['Cache-Control'] = 'public,max-age=31536000,immutable'
    }
    res.writeHead(200, headers)
    res.end(buffer)
  }
}

function serve_prerendered() {
  const serve = serve_assets(prerendered_assets)

  return (/** @type {any} */ req, /** @type {any} */ res, /** @type {() => void} */ next) => {
    let pathname = req.url.split('?')[0]
    try {
      pathname = decodeURIComponent(pathname)
    } catch {}

    if (prerendered.has(pathname)) return serve(req, res, next)

    const alt = pathname.endsWith('/') ? pathname.slice(0, -1) : pathname + '/'
    if (prerendered.has(alt)) {
      const search = req.url.includes('?') ? req.url.slice(req.url.indexOf('?')) : ''
      res.writeHead(308, { location: alt + search })
      res.end()
      return
    }

    return next()
  }
}

/** @param {any} req @returns {ReadableStream | undefined} */
function get_body(req) {
  if (!req.headers['content-type']) return undefined
  if (Number(req.headers['content-length']) === 0) return undefined

  return new ReadableStream({
    start(controller) {
      req.on('data', (/** @type {Uint8Array} */ chunk) => controller.enqueue(chunk))
      req.on('end', () => controller.close())
      req.on('error', (/** @type {Error} */ e) => controller.error(e))
    },
    cancel() {
      req.destroy()
    }
  })
}

const ssr = async (/** @type {any} */ req, /** @type {any} */ res) => {
  const base_url = `http://${req.headers['host'] ?? 'localhost'}`

  let request
  try {
    request = new Request(base_url + req.url, {
      method: req.method,
      headers: req.headers,
      body: req.method === 'GET' || req.method === 'HEAD' ? undefined : get_body(req)
    })
  } catch (e) {
    console.error('Request creation failed:', e)
    res.statusCode = 400
    res.end('Bad Request')
    return
  }

  const response = await server.respond(request, {
    platform: { req },
    getClientAddress: () => req.socket?.remoteAddress ?? '127.0.0.1'
  })

  /** @type {Record<string, string | string[]>} */
  const headers = {}
  for (const [key, value] of response.headers) {
    if (key.toLowerCase() === 'set-cookie') continue
    headers[key] = value
  }
  // Headers iteration merges duplicate values — getSetCookie() is the only
  // reliable way to retrieve individual Set-Cookie entries
  if (typeof response.headers.getSetCookie === 'function') {
    const cookies = response.headers.getSetCookie()
    if (cookies.length === 1) headers['set-cookie'] = cookies[0]
    else if (cookies.length > 1) headers['set-cookie'] = cookies
  }
  res.writeHead(response.status, headers)

  if (response.body) {
    const reader = response.body.getReader()
    try {
      for (;;) {
        const { done, value } = await reader.read()
        if (done) break
        res.write(value)
      }
    } catch (e) {
      res.destroy(e)
      return
    }
  }

  res.end()
}

function inject_ws_cookie() {
  return (/** @type {any} */ req, /** @type {any} */ res, /** @type {() => void} */ next) => {
    const token = globalThis.__BARE_WS_TOKEN
    if (!token) return next() // dev — token not set by build entry

    // Cookie already present and valid — nothing to do.
    const cookie_header = req.headers['cookie'] ?? ''
    if (cookie_header.split(';').some((c) => c.trim() === `_bwt=${token}`)) return next()

    // Wrap writeHead to append Set-Cookie on the way out.
    const orig = res.writeHead.bind(res)
    res.writeHead = (
      /** @type {number} */ status,
      /** @type {Record<string, any>} */ headers = {}
    ) => {
      const bwt = `_bwt=${token}; HttpOnly; SameSite=Strict; Path=/`
      const sc = headers['set-cookie']
      headers['set-cookie'] = sc ? (Array.isArray(sc) ? [...sc, bwt] : [sc, bwt]) : bwt
      return orig(status, headers)
    }
    next()
  }
}

/** @param {Array<(req: any, res: any, next: () => void) => void>} handlers */
function sequence(handlers) {
  return (/** @type {any} */ req, /** @type {any} */ res, /** @type {() => void} */ next) => {
    /** @param {number} i */
    function handle(i) {
      if (i < handlers.length) return handlers[i](req, res, () => handle(i + 1))
      return next()
    }
    return handle(0)
  }
}

export const handler = sequence([
  inject_ws_cookie(),
  serve_assets(client_assets, { immutable: true }),
  serve_prerendered(),
  ssr
])
