import process from 'bare-process'
import Request from 'bare-fetch/request'
import { ReadableStream } from 'bare-stream/web'

// Platform-specific asset reader. Resolved via the `imports` map in
// ./package.json: desktop → lib/read-asset.js (file:// via bare-fs),
// Android → lib/read-asset.android.js (bundle protocol).
import { read_asset } from '#read-asset'

import { Server } from 'SERVER'
import { manifest, prerendered, base } from 'MANIFEST'
// Auto-generated by adapter-bare. One import.meta.asset() call per static
// file so bare-module-traverse preserves them through bundling.
import { client as client_assets, prerendered as prerendered_assets } from './assets.js'

const server = new Server(manifest)

await server.init({
  env: /** @type {Record<string, string>} */ (process.env),
  read: (file) =>
    new ReadableStream({
      start(controller) {
        const key = (base ? base.replace(/^\//, '') + '/' : '') + file
        const resolved = client_assets[key]
        if (!resolved) return controller.error(new Error('asset not found: ' + key))
        try {
          controller.enqueue(read_asset(resolved))
          controller.close()
        } catch (e) {
          controller.error(e)
        }
      }
    })
})

/** @type {Record<string, string>} */
const MIMES = {
  html: 'text/html; charset=utf-8',
  js: 'text/javascript',
  mjs: 'text/javascript',
  css: 'text/css',
  json: 'application/json',
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  gif: 'image/gif',
  svg: 'image/svg+xml',
  ico: 'image/x-icon',
  woff: 'font/woff',
  woff2: 'font/woff2',
  ttf: 'font/ttf',
  wasm: 'application/wasm',
  webmanifest: 'application/manifest+json',
  txt: 'text/plain'
}

/** @param {string} filepath */
function get_mime(filepath) {
  const ext = filepath.split('.').pop()?.toLowerCase() ?? ''
  return MIMES[ext] ?? 'application/octet-stream'
}

/**
 * @param {Record<string, string>} assets  map of URL-relative path → asset URL
 * @param {{ immutable?: boolean }} [opts]
 */
function serve_assets(assets, opts = {}) {
  return (/** @type {any} */ req, /** @type {any} */ res, /** @type {() => void} */ next) => {
    const url = req.url.split('?')[0]
    let pathname
    try {
      pathname = decodeURIComponent(url)
    } catch {
      pathname = url
    }

    // Drop leading / and optional base prefix
    let key = pathname.replace(/^\//, '')
    if (base && key.startsWith(base.replace(/^\//, '') + '/')) {
      key = key.slice(base.replace(/^\//, '').length + 1)
    }

    let asset_url = assets[key]
    if (!asset_url && (key === '' || key.endsWith('/'))) {
      asset_url = assets[key + 'index.html']
    }
    if (!asset_url) return next()

    let buffer
    try {
      buffer = read_asset(asset_url)
    } catch (e) {
      console.error('[assets] read failed:', asset_url, e)
      res.writeHead(500, { 'Content-Type': 'text/plain' })
      res.end('asset read error')
      return
    }

    /** @type {Record<string, string | number>} */
    const headers = {
      'Content-Type': get_mime(asset_url),
      'Content-Length': buffer.byteLength
    }
    if (opts.immutable && pathname.startsWith(`/${manifest.appPath}/immutable/`)) {
      headers['Cache-Control'] = 'public,max-age=31536000,immutable'
    }
    res.writeHead(200, headers)
    res.end(buffer)
  }
}

function serve_prerendered() {
  const serve = serve_assets(prerendered_assets)

  return (/** @type {any} */ req, /** @type {any} */ res, /** @type {() => void} */ next) => {
    let pathname = req.url.split('?')[0]
    try {
      pathname = decodeURIComponent(pathname)
    } catch {}

    if (prerendered.has(pathname)) return serve(req, res, next)

    const alt = pathname.endsWith('/') ? pathname.slice(0, -1) : pathname + '/'
    if (prerendered.has(alt)) {
      const search = req.url.includes('?') ? req.url.slice(req.url.indexOf('?')) : ''
      res.writeHead(308, { location: alt + search })
      res.end()
      return
    }

    return next()
  }
}

/** @param {any} req @returns {ReadableStream | undefined} */
function get_body(req) {
  if (!req.headers['content-type']) return undefined
  if (Number(req.headers['content-length']) === 0) return undefined

  return new ReadableStream({
    start(controller) {
      req.on('data', (/** @type {Uint8Array} */ chunk) => controller.enqueue(chunk))
      req.on('end', () => controller.close())
      req.on('error', (/** @type {Error} */ e) => controller.error(e))
    },
    cancel() {
      req.destroy()
    }
  })
}

const ssr = async (/** @type {any} */ req, /** @type {any} */ res) => {
  const base_url = `http://${req.headers['host'] ?? 'localhost'}`

  let request
  try {
    request = new Request(base_url + req.url, {
      method: req.method,
      headers: req.headers,
      body: req.method === 'GET' || req.method === 'HEAD' ? undefined : get_body(req)
    })
  } catch (e) {
    console.error('Request creation failed:', e)
    res.statusCode = 400
    res.end('Bad Request')
    return
  }

  const response = await server.respond(request, {
    platform: { req },
    getClientAddress: () => req.socket?.remoteAddress ?? '127.0.0.1'
  })

  /** @type {Record<string, string>} */
  const headers = {}
  for (const [key, value] of response.headers) {
    headers[key] = value
  }
  res.writeHead(response.status, headers)

  if (response.body) {
    const reader = response.body.getReader()
    try {
      for (;;) {
        const { done, value } = await reader.read()
        if (done) break
        res.write(value)
      }
    } catch (e) {
      res.destroy(e)
      return
    }
  }

  res.end()
}

/** @param {Array<(req: any, res: any, next: () => void) => void>} handlers */
function sequence(handlers) {
  return (/** @type {any} */ req, /** @type {any} */ res, /** @type {() => void} */ next) => {
    /** @param {number} i */
    function handle(i) {
      if (i < handlers.length) return handlers[i](req, res, () => handle(i + 1))
      return next()
    }
    return handle(0)
  }
}

export const handler = sequence([
  serve_assets(client_assets, { immutable: true }),
  serve_prerendered(),
  ssr
])
